version: "3.9"
services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./migrations/storage:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5577:5432"