logger:
  level: "debug"
  inFile: "./logs/app.log"
  development: false
  disableCaller: false
  disableStacktrace: true
  encoding: "json"

statistic:
  filePath: "/Users/alexander/GolandProjects/AvitoTask/logs/data.csv"

Postgres:
  host: "localhost"
  port: "5577"
  user: "postgres"
  password: "postgres"
  DBName: "postgres"
  pgDriver: "pgx"


Server:
  AppVersion: "1.0.0"
  Host: "0.0.0.0"
  Port: "11000"